// src/app/refund-policy/page.js
import LegalPageLayout from '@/components/layout/LegalPageLayout'

export const metadata = {
  title: 'Refund Policy — WishPanda',
  description: 'Learn about refund eligibility and how to request a refund on WishPanda.',
}

export default function RefundPolicyPage() {
  return (
    <LegalPageLayout title="Refund Policy" lastUpdated="March 10, 2026">

      <h2>Overview</h2>
      <p>
        At WishPanda, we want you to be satisfied with your purchase. This Refund Policy
        outlines the conditions under which you may request a refund for paid subscriptions.
      </p>

      <h2>Eligibility for Refunds</h2>
      <p>You may be eligible for a refund if:</p>
      <ul>
        <li>You request a refund within <strong>7 days</strong> of your initial purchase</li>
        <li>You were charged incorrectly or experienced a billing error</li>
        <li>The service was significantly unavailable or non-functional during your subscription period</li>
        <li>You were charged after cancelling your subscription before the renewal date</li>
      </ul>

      <h2>Timeframe for Refund Requests</h2>
      <p>
        All refund requests must be submitted within <strong>7 days</strong> of the charge.
        Requests made after this period will be reviewed on a case-by-case basis but are
        not guaranteed.
      </p>

      <h2>Non-Refundable Cases</h2>
      <p>Refunds are generally not available for:</p>
      <ul>
        <li>Subscriptions that have been actively used for more than 7 days</li>
        <li>Partial months of service — subscriptions are charged monthly and are not prorated</li>
        <li>Dissatisfaction with gift suggestions generated by the app</li>
        <li>Failure to cancel your subscription before the renewal date</li>
        <li>Account termination due to violation of our Terms of Service</li>
      </ul>

      <h2>How to Request a Refund</h2>
      <p>To request a refund, please follow these steps:</p>
      <ul>
        <li>Send an email to <a href="mailto:support@wishpanda.space">support@wishpanda.space</a> with the subject line "Refund Request"</li>
        <li>Include your account email address</li>
        <li>Provide the date of the charge you are requesting a refund for</li>
        <li>Briefly describe the reason for your request</li>
      </ul>
      <p>
        We aim to respond to all refund requests within <strong>3–5 business days</strong>.
        Approved refunds will be processed to the original payment method within
        5–10 business days.
      </p>

      <h2>Contact Us</h2>
      <p>
        If you have any questions about our Refund Policy, please reach out
        at <a href="mailto:support@wishpanda.space">support@wishpanda.space</a> or
        visit our <a href="/contact">Contact page</a>.
      </p>

    </LegalPageLayout>
  )
}